// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	actionRecordFieldNames          = builder.RawFieldNames(&ActionRecord{})
	actionRecordRows                = strings.Join(actionRecordFieldNames, ",")
	actionRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(actionRecordFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	actionRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(actionRecordFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheActionRecordIdPrefix        = "cache:actionRecord:id:"
	cacheActionRecordUidActionPrefix = "cache:actionRecord:uid:action:"
)

type (
	actionRecordModel interface {
		Insert(ctx context.Context, data *ActionRecord, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*ActionRecord, error)
		FindOneByUidAction(ctx context.Context, uid int64, action string) (*ActionRecord, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*ActionRecord, error)
		Update(ctx context.Context, data *ActionRecord, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*ActionRecord, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*ActionRecord, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultActionRecordModel struct {
		sqlc.CachedConn
		table string
	}

	ActionRecord struct {
		Id           int64  `db:"id"`
		Uid          int64  `db:"uid"`            // 用户id
		Location     string `db:"location"`       // 位置
		Ip           string `db:"ip"`             // ip地址
		Points       int64  `db:"points"`         // 积分
		RegisterTime int64  `db:"register_time"`  // 注册时间
		LastUsedTime int64  `db:"last_used_time"` // 上一次使用时间
		Action       string `db:"action"`         // 活动名称
		CreatedTime  int64  `db:"created_time"`   // 领取时间
	}
)

func newActionRecordModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultActionRecordModel {
	return &defaultActionRecordModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`action_record`",
	}
}

func (m *defaultActionRecordModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, id, s...)
	if err != nil {
		return err
	}

	actionRecordIdKey := fmt.Sprintf("%s%v", cacheActionRecordIdPrefix, id)
	actionRecordUidActionKey := fmt.Sprintf("%s%v:%v", cacheActionRecordUidActionPrefix, data.Uid, data.Action)

	var query string
	if ActionRecordSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, actionRecordIdKey, actionRecordUidActionKey)
	return err
}

func (m *defaultActionRecordModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*ActionRecord, error) {
	actionRecordIdKey := fmt.Sprintf("%s%v", cacheActionRecordIdPrefix, id)
	var resp ActionRecord
	err := m.QueryRowCtx(ctx, &resp, actionRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", actionRecordRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActionRecordModel) FindOneByUidAction(ctx context.Context, uid int64, action string) (*ActionRecord, error) {
	actionRecordUidActionKey := fmt.Sprintf("%s%v:%v", cacheActionRecordUidActionPrefix, uid, action)
	var resp ActionRecord
	err := m.QueryRowIndexCtx(ctx, &resp, actionRecordUidActionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `uid` = ? and `action` = ? limit 1", actionRecordRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, action); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActionRecordModel) Insert(ctx context.Context, data *ActionRecord, s ...sqlx.Session) (sql.Result, error) {
	actionRecordIdKey := fmt.Sprintf("%s%v", cacheActionRecordIdPrefix, data.Id)
	actionRecordUidActionKey := fmt.Sprintf("%s%v:%v", cacheActionRecordUidActionPrefix, data.Uid, data.Action)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, actionRecordRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.Location, data.Ip, data.Points, data.RegisterTime, data.LastUsedTime, data.Action, data.CreatedTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Location, data.Ip, data.Points, data.RegisterTime, data.LastUsedTime, data.Action, data.CreatedTime)
	}, actionRecordIdKey, actionRecordUidActionKey)
}

func (m *defaultActionRecordModel) Update(ctx context.Context, newData *ActionRecord, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, newData.Id, s...)
	if err != nil {
		return err
	}

	actionRecordIdKey := fmt.Sprintf("%s%v", cacheActionRecordIdPrefix, data.Id)
	actionRecordUidActionKey := fmt.Sprintf("%s%v:%v", cacheActionRecordUidActionPrefix, data.Uid, data.Action)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, actionRecordRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, newData.Uid, newData.Location, newData.Ip, newData.Points, newData.RegisterTime, newData.LastUsedTime, newData.Action, newData.CreatedTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Uid, newData.Location, newData.Ip, newData.Points, newData.RegisterTime, newData.LastUsedTime, newData.Action, newData.CreatedTime, newData.Id)
	}, actionRecordIdKey, actionRecordUidActionKey)
	return err
}

func (m *defaultActionRecordModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*ActionRecord, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(actionRecordRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret ActionRecord
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultActionRecordModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*ActionRecord, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(actionRecordRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*ActionRecord
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultActionRecordModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*ActionRecord, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(actionRecordRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*ActionRecord
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultActionRecordModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultActionRecordModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheActionRecordIdPrefix, primary)
}

func (m *defaultActionRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", actionRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultActionRecordModel) tableName() string {
	return m.table
}

var ActionRecordSoftDelete bool

func init() {
	tp := reflect.TypeOf(ActionRecord{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			ActionRecordSoftDelete = true
			return
		}
	}
}
