// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminFieldNames          = builder.RawFieldNames(&Admin{})
	adminRows                = strings.Join(adminFieldNames, ",")
	adminRowsExpectAutoSet   = strings.Join(stringx.Remove(adminFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	adminRowsWithPlaceHolder = strings.Join(stringx.Remove(adminFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheAdminIdPrefix                 = "cache:admin:id:"
	cacheAdminAccountDeletedTimePrefix = "cache:admin:account:deletedTime:"
)

type (
	adminModel interface {
		Insert(ctx context.Context, data *Admin, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*Admin, error)
		FindOneByAccountDeletedTime(ctx context.Context, account string, deletedTime int64) (*Admin, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*Admin, error)
		Update(ctx context.Context, data *Admin, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*Admin, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*Admin, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultAdminModel struct {
		sqlc.CachedConn
		table string
	}

	Admin struct {
		Id          int64  `db:"id"`
		Account     string `db:"account"`    // 账户
		Password    string `db:"password"`   // 用户密码
		Avatar      string `db:"avatar"`     // 头像路径
		IsDisable   int64  `db:"is_disable"` // 是否禁用 1禁用 2启用
		Remark      string `db:"remark"`     // 备注
		LastTime    int64  `db:"last_time"`  // 最后登录时间
		CreatedTime int64  `db:"created_time"`
		UpdatedTime int64  `db:"updated_time"`
		DeletedTime int64  `db:"deleted_time"`
	}
)

func newAdminModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAdminModel {
	return &defaultAdminModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`admin`",
	}
}

func (m *defaultAdminModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, id, s...)
	if err != nil {
		return err
	}

	adminAccountDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheAdminAccountDeletedTimePrefix, data.Account, data.DeletedTime)
	adminIdKey := fmt.Sprintf("%s%v", cacheAdminIdPrefix, id)

	var query string
	if AdminSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, adminAccountDeletedTimeKey, adminIdKey)
	return err
}

func (m *defaultAdminModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*Admin, error) {
	adminIdKey := fmt.Sprintf("%s%v", cacheAdminIdPrefix, id)
	var resp Admin
	err := m.QueryRowCtx(ctx, &resp, adminIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) FindOneByAccountDeletedTime(ctx context.Context, account string, deletedTime int64) (*Admin, error) {
	adminAccountDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheAdminAccountDeletedTimePrefix, account, deletedTime)
	var resp Admin
	err := m.QueryRowIndexCtx(ctx, &resp, adminAccountDeletedTimeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `account` = ? and `deleted_time` = ? limit 1", adminRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, account, deletedTime); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) Insert(ctx context.Context, data *Admin, s ...sqlx.Session) (sql.Result, error) {
	adminAccountDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheAdminAccountDeletedTimePrefix, data.Account, data.DeletedTime)
	adminIdKey := fmt.Sprintf("%s%v", cacheAdminIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, adminRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Account, data.Password, data.Avatar, data.IsDisable, data.Remark, data.LastTime, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Account, data.Password, data.Avatar, data.IsDisable, data.Remark, data.LastTime, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, adminAccountDeletedTimeKey, adminIdKey)
}

func (m *defaultAdminModel) Update(ctx context.Context, newData *Admin, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, newData.Id, s...)
	if err != nil {
		return err
	}

	adminAccountDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheAdminAccountDeletedTimePrefix, data.Account, data.DeletedTime)
	adminIdKey := fmt.Sprintf("%s%v", cacheAdminIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, newData.Account, newData.Password, newData.Avatar, newData.IsDisable, newData.Remark, newData.LastTime, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Account, newData.Password, newData.Avatar, newData.IsDisable, newData.Remark, newData.LastTime, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
	}, adminAccountDeletedTimeKey, adminIdKey)
	return err
}

func (m *defaultAdminModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*Admin, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(adminRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret Admin
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultAdminModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*Admin, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(adminRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*Admin
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultAdminModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*Admin, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(adminRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*Admin
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultAdminModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultAdminModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAdminIdPrefix, primary)
}

func (m *defaultAdminModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminModel) tableName() string {
	return m.table
}

var AdminSoftDelete bool

func init() {
	tp := reflect.TypeOf(Admin{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			AdminSoftDelete = true
			return
		}
	}
}
