// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dictFieldNames          = builder.RawFieldNames(&Dict{})
	dictRows                = strings.Join(dictFieldNames, ",")
	dictRowsExpectAutoSet   = strings.Join(stringx.Remove(dictFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	dictRowsWithPlaceHolder = strings.Join(stringx.Remove(dictFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheDictIdPrefix              = "cache:dict:id:"
	cacheDictCodeDeletedTimePrefix = "cache:dict:code:deletedTime:"
)

type (
	dictModel interface {
		Insert(ctx context.Context, data *Dict, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*Dict, error)
		FindOneByCodeDeletedTime(ctx context.Context, code string, deletedTime int64) (*Dict, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*Dict, error)
		Update(ctx context.Context, data *Dict, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*Dict, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*Dict, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultDictModel struct {
		sqlc.CachedConn
		table string
	}

	Dict struct {
		Id          int64  `db:"id"`           // 主键
		Code        string `db:"code"`         // 字典唯一ID 标识符
		ParamType   int64  `db:"param_type"`   // 类型 1注册奖励 2引荐奖励 3活动规则 4其他设置 5邀请奖励
		Name        string `db:"name"`         // 字典名称
		Desc        string `db:"desc"`         // 字典说明
		Value       string `db:"value"`        // 字典内容信息
		BackupValue int64  `db:"backup_value"` // 字典内容信息
		Fixed       int64  `db:"fixed"`        // 是否为固定字典 1是2否
		CreatedTime int64  `db:"created_time"`
		UpdatedTime int64  `db:"updated_time"`
		DeletedTime int64  `db:"deleted_time"`
	}
)

func newDictModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultDictModel {
	return &defaultDictModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`dict`",
	}
}

func (m *defaultDictModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, id, s...)
	if err != nil {
		return err
	}

	dictCodeDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheDictCodeDeletedTimePrefix, data.Code, data.DeletedTime)
	dictIdKey := fmt.Sprintf("%s%v", cacheDictIdPrefix, id)

	var query string
	if DictSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, dictCodeDeletedTimeKey, dictIdKey)
	return err
}

func (m *defaultDictModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*Dict, error) {
	dictIdKey := fmt.Sprintf("%s%v", cacheDictIdPrefix, id)
	var resp Dict
	err := m.QueryRowCtx(ctx, &resp, dictIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dictRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDictModel) FindOneByCodeDeletedTime(ctx context.Context, code string, deletedTime int64) (*Dict, error) {
	dictCodeDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheDictCodeDeletedTimePrefix, code, deletedTime)
	var resp Dict
	err := m.QueryRowIndexCtx(ctx, &resp, dictCodeDeletedTimeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? and `deleted_time` = ? limit 1", dictRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code, deletedTime); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDictModel) Insert(ctx context.Context, data *Dict, s ...sqlx.Session) (sql.Result, error) {
	dictCodeDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheDictCodeDeletedTimePrefix, data.Code, data.DeletedTime)
	dictIdKey := fmt.Sprintf("%s%v", cacheDictIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dictRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Code, data.ParamType, data.Name, data.Desc, data.Value, data.BackupValue, data.Fixed, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Code, data.ParamType, data.Name, data.Desc, data.Value, data.BackupValue, data.Fixed, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, dictCodeDeletedTimeKey, dictIdKey)
}

func (m *defaultDictModel) Update(ctx context.Context, newData *Dict, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, newData.Id, s...)
	if err != nil {
		return err
	}

	dictCodeDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheDictCodeDeletedTimePrefix, data.Code, data.DeletedTime)
	dictIdKey := fmt.Sprintf("%s%v", cacheDictIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dictRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, newData.Code, newData.ParamType, newData.Name, newData.Desc, newData.Value, newData.BackupValue, newData.Fixed, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Code, newData.ParamType, newData.Name, newData.Desc, newData.Value, newData.BackupValue, newData.Fixed, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
	}, dictCodeDeletedTimeKey, dictIdKey)
	return err
}

func (m *defaultDictModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*Dict, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(dictRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret Dict
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultDictModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*Dict, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(dictRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*Dict
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultDictModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*Dict, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(dictRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*Dict
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultDictModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultDictModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDictIdPrefix, primary)
}

func (m *defaultDictModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dictRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDictModel) tableName() string {
	return m.table
}

var DictSoftDelete bool

func init() {
	tp := reflect.TypeOf(Dict{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			DictSoftDelete = true
			return
		}
	}
}
