// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskPoolFieldNames          = builder.RawFieldNames(&TaskPool{})
	taskPoolRows                = strings.Join(taskPoolFieldNames, ",")
	taskPoolRowsExpectAutoSet   = strings.Join(stringx.Remove(taskPoolFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	taskPoolRowsWithPlaceHolder = strings.Join(stringx.Remove(taskPoolFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheTaskPoolIdPrefix = "cache:taskPool:id:"
)

type (
	taskPoolModel interface {
		Insert(ctx context.Context, data *TaskPool, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*TaskPool, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*TaskPool, error)
		Update(ctx context.Context, data *TaskPool, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*TaskPool, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*TaskPool, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultTaskPoolModel struct {
		sqlc.CachedConn
		table string
	}

	TaskPool struct {
		Id          int64  `db:"id"`
		TaskType    int64  `db:"task_type"`    // 任务类型 1入职2探索3邀请4奖励
		TaskName    string `db:"task_name"`    // 任务名
		TaskNameEn  string `db:"task_name_en"` // 英文任务名
		Sort        int64  `db:"sort"`         // 排序
		Integral    int64  `db:"integral"`     // 奖励积分
		Remark      string `db:"remark"`       // 简介
		IsDisable   int64  `db:"is_disable"`   // 是否禁用 1禁用 2启用
		Link        string `db:"link"`         // 链接
		CreatedTime int64  `db:"created_time"`
		UpdatedTime int64  `db:"updated_time"`
		DeletedTime int64  `db:"deleted_time"`
	}
)

func newTaskPoolModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTaskPoolModel {
	return &defaultTaskPoolModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`task_pool`",
	}
}

func (m *defaultTaskPoolModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	taskPoolIdKey := fmt.Sprintf("%s%v", cacheTaskPoolIdPrefix, id)

	var query string
	if TaskPoolSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, taskPoolIdKey)
	return err
}

func (m *defaultTaskPoolModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*TaskPool, error) {
	taskPoolIdKey := fmt.Sprintf("%s%v", cacheTaskPoolIdPrefix, id)
	var resp TaskPool
	err := m.QueryRowCtx(ctx, &resp, taskPoolIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskPoolRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskPoolModel) Insert(ctx context.Context, data *TaskPool, s ...sqlx.Session) (sql.Result, error) {
	taskPoolIdKey := fmt.Sprintf("%s%v", cacheTaskPoolIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, taskPoolRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.TaskType, data.TaskName, data.TaskNameEn, data.Sort, data.Integral, data.Remark, data.IsDisable, data.Link, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.TaskType, data.TaskName, data.TaskNameEn, data.Sort, data.Integral, data.Remark, data.IsDisable, data.Link, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, taskPoolIdKey)
}

func (m *defaultTaskPoolModel) Update(ctx context.Context, data *TaskPool, s ...sqlx.Session) error {
	taskPoolIdKey := fmt.Sprintf("%s%v", cacheTaskPoolIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taskPoolRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.TaskType, data.TaskName, data.TaskNameEn, data.Sort, data.Integral, data.Remark, data.IsDisable, data.Link, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.TaskType, data.TaskName, data.TaskNameEn, data.Sort, data.Integral, data.Remark, data.IsDisable, data.Link, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
	}, taskPoolIdKey)
	return err
}

func (m *defaultTaskPoolModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*TaskPool, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(taskPoolRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret TaskPool
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultTaskPoolModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*TaskPool, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(taskPoolRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*TaskPool
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultTaskPoolModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*TaskPool, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(taskPoolRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*TaskPool
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultTaskPoolModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultTaskPoolModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTaskPoolIdPrefix, primary)
}

func (m *defaultTaskPoolModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskPoolRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTaskPoolModel) tableName() string {
	return m.table
}

var TaskPoolSoftDelete bool

func init() {
	tp := reflect.TypeOf(TaskPool{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			TaskPoolSoftDelete = true
			return
		}
	}
}
