// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userStorageExchangeFieldNames          = builder.RawFieldNames(&UserStorageExchange{})
	userStorageExchangeRows                = strings.Join(userStorageExchangeFieldNames, ",")
	userStorageExchangeRowsExpectAutoSet   = strings.Join(stringx.Remove(userStorageExchangeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userStorageExchangeRowsWithPlaceHolder = strings.Join(stringx.Remove(userStorageExchangeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserStorageExchangeIdPrefix = "cache:userStorageExchange:id:"
)

type (
	userStorageExchangeModel interface {
		Insert(ctx context.Context, data *UserStorageExchange, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserStorageExchange, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserStorageExchange, error)
		Update(ctx context.Context, data *UserStorageExchange, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserStorageExchange, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserStorageExchange, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultUserStorageExchangeModel struct {
		sqlc.CachedConn
		table string
	}

	UserStorageExchange struct {
		Id              int64 `db:"id"`
		Uid             int64 `db:"uid"`
		ExchangeStorage int64 `db:"exchange_storage"` // 兑换空间
		CreatedTime     int64 `db:"created_time"`
		UpdatedTime     int64 `db:"updated_time"`
		DeletedTime     int64 `db:"deleted_time"`
	}
)

func newUserStorageExchangeModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserStorageExchangeModel {
	return &defaultUserStorageExchangeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_storage_exchange`",
	}
}

func (m *defaultUserStorageExchangeModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	userStorageExchangeIdKey := fmt.Sprintf("%s%v", cacheUserStorageExchangeIdPrefix, id)

	var query string
	if UserStorageExchangeSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, userStorageExchangeIdKey)
	return err
}

func (m *defaultUserStorageExchangeModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserStorageExchange, error) {
	userStorageExchangeIdKey := fmt.Sprintf("%s%v", cacheUserStorageExchangeIdPrefix, id)
	var resp UserStorageExchange
	err := m.QueryRowCtx(ctx, &resp, userStorageExchangeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStorageExchangeRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStorageExchangeModel) Insert(ctx context.Context, data *UserStorageExchange, s ...sqlx.Session) (sql.Result, error) {
	userStorageExchangeIdKey := fmt.Sprintf("%s%v", cacheUserStorageExchangeIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userStorageExchangeRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.ExchangeStorage, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.ExchangeStorage, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, userStorageExchangeIdKey)
}

func (m *defaultUserStorageExchangeModel) Update(ctx context.Context, data *UserStorageExchange, s ...sqlx.Session) error {
	userStorageExchangeIdKey := fmt.Sprintf("%s%v", cacheUserStorageExchangeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userStorageExchangeRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.ExchangeStorage, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.ExchangeStorage, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
	}, userStorageExchangeIdKey)
	return err
}

func (m *defaultUserStorageExchangeModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserStorageExchange, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userStorageExchangeRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret UserStorageExchange
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultUserStorageExchangeModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserStorageExchange, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(userStorageExchangeRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*UserStorageExchange
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultUserStorageExchangeModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserStorageExchange, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userStorageExchangeRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*UserStorageExchange
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultUserStorageExchangeModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultUserStorageExchangeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserStorageExchangeIdPrefix, primary)
}

func (m *defaultUserStorageExchangeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStorageExchangeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserStorageExchangeModel) tableName() string {
	return m.table
}

var UserStorageExchangeSoftDelete bool

func init() {
	tp := reflect.TypeOf(UserStorageExchange{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			UserStorageExchangeSoftDelete = true
			return
		}
	}
}
