// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userStorageFieldNames          = builder.RawFieldNames(&UserStorage{})
	userStorageRows                = strings.Join(userStorageFieldNames, ",")
	userStorageRowsExpectAutoSet   = strings.Join(stringx.Remove(userStorageFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userStorageRowsWithPlaceHolder = strings.Join(stringx.Remove(userStorageFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserStorageIdPrefix             = "cache:userStorage:id:"
	cacheUserStorageUidDeletedTimePrefix = "cache:userStorage:uid:deletedTime:"
)

type (
	userStorageModel interface {
		Insert(ctx context.Context, data *UserStorage, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserStorage, error)
		FindOneByUidDeletedTime(ctx context.Context, uid int64, deletedTime int64) (*UserStorage, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserStorage, error)
		Update(ctx context.Context, data *UserStorage, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserStorage, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserStorage, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultUserStorageModel struct {
		sqlc.CachedConn
		table string
	}

	UserStorage struct {
		Id          int64 `db:"id"`
		Uid         int64 `db:"uid"`
		Storage     int64 `db:"storage"`     // 存储空间
		StorageUse  int64 `db:"storage_use"` // 使用空间
		CreatedTime int64 `db:"created_time"`
		UpdatedTime int64 `db:"updated_time"`
		DeletedTime int64 `db:"deleted_time"`
	}
)

func newUserStorageModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserStorageModel {
	return &defaultUserStorageModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_storage`",
	}
}

func (m *defaultUserStorageModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, id, s...)
	if err != nil {
		return err
	}

	userStorageIdKey := fmt.Sprintf("%s%v", cacheUserStorageIdPrefix, id)
	userStorageUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserStorageUidDeletedTimePrefix, data.Uid, data.DeletedTime)

	var query string
	if UserStorageSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, userStorageIdKey, userStorageUidDeletedTimeKey)
	return err
}

func (m *defaultUserStorageModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserStorage, error) {
	userStorageIdKey := fmt.Sprintf("%s%v", cacheUserStorageIdPrefix, id)
	var resp UserStorage
	err := m.QueryRowCtx(ctx, &resp, userStorageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStorageRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStorageModel) FindOneByUidDeletedTime(ctx context.Context, uid int64, deletedTime int64) (*UserStorage, error) {
	userStorageUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserStorageUidDeletedTimePrefix, uid, deletedTime)
	var resp UserStorage
	err := m.QueryRowIndexCtx(ctx, &resp, userStorageUidDeletedTimeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `uid` = ? and `deleted_time` = ? limit 1", userStorageRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, deletedTime); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStorageModel) Insert(ctx context.Context, data *UserStorage, s ...sqlx.Session) (sql.Result, error) {
	userStorageIdKey := fmt.Sprintf("%s%v", cacheUserStorageIdPrefix, data.Id)
	userStorageUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserStorageUidDeletedTimePrefix, data.Uid, data.DeletedTime)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userStorageRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.Storage, data.StorageUse, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Storage, data.StorageUse, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, userStorageIdKey, userStorageUidDeletedTimeKey)
}

func (m *defaultUserStorageModel) Update(ctx context.Context, newData *UserStorage, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, newData.Id, s...)
	if err != nil {
		return err
	}

	userStorageIdKey := fmt.Sprintf("%s%v", cacheUserStorageIdPrefix, data.Id)
	userStorageUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserStorageUidDeletedTimePrefix, data.Uid, data.DeletedTime)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userStorageRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, newData.Uid, newData.Storage, newData.StorageUse, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Uid, newData.Storage, newData.StorageUse, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
	}, userStorageIdKey, userStorageUidDeletedTimeKey)
	return err
}

func (m *defaultUserStorageModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserStorage, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userStorageRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret UserStorage
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultUserStorageModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserStorage, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(userStorageRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*UserStorage
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultUserStorageModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserStorage, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userStorageRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*UserStorage
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultUserStorageModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultUserStorageModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserStorageIdPrefix, primary)
}

func (m *defaultUserStorageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStorageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserStorageModel) tableName() string {
	return m.table
}

var UserStorageSoftDelete bool

func init() {
	tp := reflect.TypeOf(UserStorage{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			UserStorageSoftDelete = true
			return
		}
	}
}
