// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPointsFieldNames          = builder.RawFieldNames(&UserPoints{})
	userPointsRows                = strings.Join(userPointsFieldNames, ",")
	userPointsRowsExpectAutoSet   = strings.Join(stringx.Remove(userPointsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userPointsRowsWithPlaceHolder = strings.Join(stringx.Remove(userPointsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserPointsIdPrefix             = "cache:userPoints:id:"
	cacheUserPointsUidDeletedTimePrefix = "cache:userPoints:uid:deletedTime:"
)

type (
	userPointsModel interface {
		Insert(ctx context.Context, data *UserPoints, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserPoints, error)
		FindOneByUidDeletedTime(ctx context.Context, uid int64, deletedTime int64) (*UserPoints, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserPoints, error)
		Update(ctx context.Context, data *UserPoints, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserPoints, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserPoints, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultUserPointsModel struct {
		sqlc.CachedConn
		table string
	}

	UserPoints struct {
		Id          int64 `db:"id"`
		Uid         int64 `db:"uid"`
		Points      int64 `db:"points"`     // 积分
		ReqPoints   int64 `db:"req_points"` // 邀请积分
		CreatedTime int64 `db:"created_time"`
		UpdatedTime int64 `db:"updated_time"`
		DeletedTime int64 `db:"deleted_time"`
	}
)

func newUserPointsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserPointsModel {
	return &defaultUserPointsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_points`",
	}
}

func (m *defaultUserPointsModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, id, s...)
	if err != nil {
		return err
	}

	userPointsIdKey := fmt.Sprintf("%s%v", cacheUserPointsIdPrefix, id)
	userPointsUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserPointsUidDeletedTimePrefix, data.Uid, data.DeletedTime)

	var query string
	if UserPointsSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, userPointsIdKey, userPointsUidDeletedTimeKey)
	return err
}

func (m *defaultUserPointsModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserPoints, error) {
	userPointsIdKey := fmt.Sprintf("%s%v", cacheUserPointsIdPrefix, id)
	var resp UserPoints
	err := m.QueryRowCtx(ctx, &resp, userPointsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userPointsRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointsModel) FindOneByUidDeletedTime(ctx context.Context, uid int64, deletedTime int64) (*UserPoints, error) {
	userPointsUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserPointsUidDeletedTimePrefix, uid, deletedTime)
	var resp UserPoints
	err := m.QueryRowIndexCtx(ctx, &resp, userPointsUidDeletedTimeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `uid` = ? and `deleted_time` = ? limit 1", userPointsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, deletedTime); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPointsModel) Insert(ctx context.Context, data *UserPoints, s ...sqlx.Session) (sql.Result, error) {
	userPointsIdKey := fmt.Sprintf("%s%v", cacheUserPointsIdPrefix, data.Id)
	userPointsUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserPointsUidDeletedTimePrefix, data.Uid, data.DeletedTime)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userPointsRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.Points, data.ReqPoints, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Points, data.ReqPoints, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, userPointsIdKey, userPointsUidDeletedTimeKey)
}

func (m *defaultUserPointsModel) Update(ctx context.Context, newData *UserPoints, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, newData.Id, s...)
	if err != nil {
		return err
	}

	userPointsIdKey := fmt.Sprintf("%s%v", cacheUserPointsIdPrefix, data.Id)
	userPointsUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserPointsUidDeletedTimePrefix, data.Uid, data.DeletedTime)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userPointsRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, newData.Uid, newData.Points, newData.ReqPoints, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Uid, newData.Points, newData.ReqPoints, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
	}, userPointsIdKey, userPointsUidDeletedTimeKey)
	return err
}

func (m *defaultUserPointsModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserPoints, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userPointsRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret UserPoints
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultUserPointsModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserPoints, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(userPointsRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*UserPoints
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultUserPointsModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserPoints, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userPointsRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*UserPoints
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultUserPointsModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultUserPointsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserPointsIdPrefix, primary)
}

func (m *defaultUserPointsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userPointsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserPointsModel) tableName() string {
	return m.table
}

var UserPointsSoftDelete bool

func init() {
	tp := reflect.TypeOf(UserPoints{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			UserPointsSoftDelete = true
			return
		}
	}
}
