// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInviteFieldNames          = builder.RawFieldNames(&UserInvite{})
	userInviteRows                = strings.Join(userInviteFieldNames, ",")
	userInviteRowsExpectAutoSet   = strings.Join(stringx.Remove(userInviteFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userInviteRowsWithPlaceHolder = strings.Join(stringx.Remove(userInviteFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserInviteIdPrefix = "cache:userInvite:id:"
)

type (
	userInviteModel interface {
		Insert(ctx context.Context, data *UserInvite, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserInvite, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserInvite, error)
		Update(ctx context.Context, data *UserInvite, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserInvite, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserInvite, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultUserInviteModel struct {
		sqlc.CachedConn
		table string
	}

	UserInvite struct {
		Id           int64 `db:"id"`
		Pid          int64 `db:"pid"`
		Uid          int64 `db:"uid"`
		InvitePoints int64 `db:"invite_points"` // 邀请获得积分
		CreatedTime  int64 `db:"created_time"`
		UpdatedTime  int64 `db:"updated_time"`
		DeletedTime  int64 `db:"deleted_time"`
	}
)

func newUserInviteModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserInviteModel {
	return &defaultUserInviteModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_invite`",
	}
}

func (m *defaultUserInviteModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	userInviteIdKey := fmt.Sprintf("%s%v", cacheUserInviteIdPrefix, id)

	var query string
	if UserInviteSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, userInviteIdKey)
	return err
}

func (m *defaultUserInviteModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserInvite, error) {
	userInviteIdKey := fmt.Sprintf("%s%v", cacheUserInviteIdPrefix, id)
	var resp UserInvite
	err := m.QueryRowCtx(ctx, &resp, userInviteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInviteRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInviteModel) Insert(ctx context.Context, data *UserInvite, s ...sqlx.Session) (sql.Result, error) {
	userInviteIdKey := fmt.Sprintf("%s%v", cacheUserInviteIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userInviteRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Pid, data.Uid, data.InvitePoints, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Pid, data.Uid, data.InvitePoints, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, userInviteIdKey)
}

func (m *defaultUserInviteModel) Update(ctx context.Context, data *UserInvite, s ...sqlx.Session) error {
	userInviteIdKey := fmt.Sprintf("%s%v", cacheUserInviteIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userInviteRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Pid, data.Uid, data.InvitePoints, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Pid, data.Uid, data.InvitePoints, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
	}, userInviteIdKey)
	return err
}

func (m *defaultUserInviteModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserInvite, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userInviteRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret UserInvite
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultUserInviteModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserInvite, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(userInviteRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*UserInvite
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultUserInviteModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserInvite, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userInviteRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*UserInvite
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultUserInviteModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultUserInviteModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserInviteIdPrefix, primary)
}

func (m *defaultUserInviteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInviteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserInviteModel) tableName() string {
	return m.table
}

var UserInviteSoftDelete bool

func init() {
	tp := reflect.TypeOf(UserInvite{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			UserInviteSoftDelete = true
			return
		}
	}
}
