// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInviteRewardFieldNames          = builder.RawFieldNames(&UserInviteReward{})
	userInviteRewardRows                = strings.Join(userInviteRewardFieldNames, ",")
	userInviteRewardRowsExpectAutoSet   = strings.Join(stringx.Remove(userInviteRewardFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userInviteRewardRowsWithPlaceHolder = strings.Join(stringx.Remove(userInviteRewardFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserInviteRewardIdPrefix             = "cache:userInviteReward:id:"
	cacheUserInviteRewardUidDeletedTimePrefix = "cache:userInviteReward:uid:deletedTime:"
)

type (
	userInviteRewardModel interface {
		Insert(ctx context.Context, data *UserInviteReward, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserInviteReward, error)
		FindOneByUidDeletedTime(ctx context.Context, uid int64, deletedTime int64) (*UserInviteReward, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserInviteReward, error)
		Update(ctx context.Context, data *UserInviteReward, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserInviteReward, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserInviteReward, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultUserInviteRewardModel struct {
		sqlc.CachedConn
		table string
	}

	UserInviteReward struct {
		Id          int64 `db:"id"`
		Uid         int64 `db:"uid"`
		InviteNum   int64 `db:"invite_num"` // 邀请数量
		CreatedTime int64 `db:"created_time"`
		UpdatedTime int64 `db:"updated_time"`
		DeletedTime int64 `db:"deleted_time"`
	}
)

func newUserInviteRewardModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserInviteRewardModel {
	return &defaultUserInviteRewardModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_invite_reward`",
	}
}

func (m *defaultUserInviteRewardModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, id, s...)
	if err != nil {
		return err
	}

	userInviteRewardIdKey := fmt.Sprintf("%s%v", cacheUserInviteRewardIdPrefix, id)
	userInviteRewardUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserInviteRewardUidDeletedTimePrefix, data.Uid, data.DeletedTime)

	var query string
	if UserInviteRewardSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, userInviteRewardIdKey, userInviteRewardUidDeletedTimeKey)
	return err
}

func (m *defaultUserInviteRewardModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*UserInviteReward, error) {
	userInviteRewardIdKey := fmt.Sprintf("%s%v", cacheUserInviteRewardIdPrefix, id)
	var resp UserInviteReward
	err := m.QueryRowCtx(ctx, &resp, userInviteRewardIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInviteRewardRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInviteRewardModel) FindOneByUidDeletedTime(ctx context.Context, uid int64, deletedTime int64) (*UserInviteReward, error) {
	userInviteRewardUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserInviteRewardUidDeletedTimePrefix, uid, deletedTime)
	var resp UserInviteReward
	err := m.QueryRowIndexCtx(ctx, &resp, userInviteRewardUidDeletedTimeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `uid` = ? and `deleted_time` = ? limit 1", userInviteRewardRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, deletedTime); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInviteRewardModel) Insert(ctx context.Context, data *UserInviteReward, s ...sqlx.Session) (sql.Result, error) {
	userInviteRewardIdKey := fmt.Sprintf("%s%v", cacheUserInviteRewardIdPrefix, data.Id)
	userInviteRewardUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserInviteRewardUidDeletedTimePrefix, data.Uid, data.DeletedTime)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userInviteRewardRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.InviteNum, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.InviteNum, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, userInviteRewardIdKey, userInviteRewardUidDeletedTimeKey)
}

func (m *defaultUserInviteRewardModel) Update(ctx context.Context, newData *UserInviteReward, s ...sqlx.Session) error {
	data, err := m.FindOne(ctx, newData.Id, s...)
	if err != nil {
		return err
	}

	userInviteRewardIdKey := fmt.Sprintf("%s%v", cacheUserInviteRewardIdPrefix, data.Id)
	userInviteRewardUidDeletedTimeKey := fmt.Sprintf("%s%v:%v", cacheUserInviteRewardUidDeletedTimePrefix, data.Uid, data.DeletedTime)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userInviteRewardRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, newData.Uid, newData.InviteNum, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Uid, newData.InviteNum, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Id)
	}, userInviteRewardIdKey, userInviteRewardUidDeletedTimeKey)
	return err
}

func (m *defaultUserInviteRewardModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*UserInviteReward, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userInviteRewardRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret UserInviteReward
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultUserInviteRewardModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*UserInviteReward, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(userInviteRewardRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*UserInviteReward
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultUserInviteRewardModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*UserInviteReward, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(userInviteRewardRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*UserInviteReward
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultUserInviteRewardModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultUserInviteRewardModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserInviteRewardIdPrefix, primary)
}

func (m *defaultUserInviteRewardModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInviteRewardRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserInviteRewardModel) tableName() string {
	return m.table
}

var UserInviteRewardSoftDelete bool

func init() {
	tp := reflect.TypeOf(UserInviteReward{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			UserInviteRewardSoftDelete = true
			return
		}
	}
}
