// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "T-driver/app/video/api/internal/handler/comment"
	label "T-driver/app/video/api/internal/handler/label"
	reply "T-driver/app/video/api/internal/handler/reply"
	video "T-driver/app/video/api/internal/handler/video"
	"T-driver/app/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/videoList",
					Handler: video.VideoListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/video"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/labelList",
					Handler: label.LabelListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/labelAdd",
					Handler: label.LabelAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/labelUserLike",
					Handler: label.LabelUserLikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/video/label"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/commentList",
					Handler: comment.CommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/commentAdd",
					Handler: comment.CommentAddHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/video/comment"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/replyList",
					Handler: reply.ReplyListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/replyAdd",
					Handler: reply.ReplyAddHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/video/reply"),
	)
}
