// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bot "T-driver/app/tgbot/api/internal/handler/bot"
	"T-driver/app/tgbot/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/webhook",
				Handler: bot.BotWebhookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/titanCallback",
				Handler: bot.TitanCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/bot"),
	)
}
