// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: app/tgbot/rpc/proto/tgbot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBotMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text   string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`      //发送的消息
	ChatID int64  `protobuf:"varint,2,opt,name=chatID,proto3" json:"chatID,omitempty"` //发送用户id
}

func (x *SendBotMsgRequest) Reset() {
	*x = SendBotMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotMsgRequest) ProtoMessage() {}

func (x *SendBotMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotMsgRequest.ProtoReflect.Descriptor instead.
func (*SendBotMsgRequest) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{0}
}

func (x *SendBotMsgRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendBotMsgRequest) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

type SendBotMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendBotMsgResponse) Reset() {
	*x = SendBotMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotMsgResponse) ProtoMessage() {}

func (x *SendBotMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotMsgResponse.ProtoReflect.Descriptor instead.
func (*SendBotMsgResponse) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{1}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Button       string `protobuf:"bytes,1,opt,name=Button,proto3" json:"Button,omitempty"`             //按钮
	Url          string `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`                   //链接
	CallbackData string `protobuf:"bytes,3,opt,name=CallbackData,proto3" json:"CallbackData,omitempty"` //回调数据
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Item) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

type Markup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Markup []*Item `protobuf:"bytes,1,rep,name=markup,proto3" json:"markup,omitempty"`
}

func (x *Markup) Reset() {
	*x = Markup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Markup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Markup) ProtoMessage() {}

func (x *Markup) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Markup.ProtoReflect.Descriptor instead.
func (*Markup) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{3}
}

func (x *Markup) GetMarkup() []*Item {
	if x != nil {
		return x.Markup
	}
	return nil
}

type SendPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId           string    `protobuf:"bytes,2,opt,name=chatId,proto3" json:"chatId,omitempty"`   //发送用户id或者频道名称
	Photo            []byte    `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`     //图片
	Caption          string    `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"` //描述
	ReplyMarkup      []*Markup `protobuf:"bytes,4,rep,name=replyMarkup,proto3" json:"replyMarkup,omitempty"`
	IsPinChatMessage bool      `protobuf:"varint,5,opt,name=isPinChatMessage,proto3" json:"isPinChatMessage,omitempty"`
}

func (x *SendPhotoRequest) Reset() {
	*x = SendPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhotoRequest) ProtoMessage() {}

func (x *SendPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhotoRequest.ProtoReflect.Descriptor instead.
func (*SendPhotoRequest) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{4}
}

func (x *SendPhotoRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendPhotoRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *SendPhotoRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *SendPhotoRequest) GetReplyMarkup() []*Markup {
	if x != nil {
		return x.ReplyMarkup
	}
	return nil
}

func (x *SendPhotoRequest) GetIsPinChatMessage() bool {
	if x != nil {
		return x.IsPinChatMessage
	}
	return false
}

type DelPinMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatID int64 `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"` //发送用户id
	MsgID  int64 `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`   //消息id
}

func (x *DelPinMsgReq) Reset() {
	*x = DelPinMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPinMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPinMsgReq) ProtoMessage() {}

func (x *DelPinMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPinMsgReq.ProtoReflect.Descriptor instead.
func (*DelPinMsgReq) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{5}
}

func (x *DelPinMsgReq) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

func (x *DelPinMsgReq) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

type DelAllPinMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatID int64 `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
}

func (x *DelAllPinMsgReq) Reset() {
	*x = DelAllPinMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelAllPinMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelAllPinMsgReq) ProtoMessage() {}

func (x *DelAllPinMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelAllPinMsgReq.ProtoReflect.Descriptor instead.
func (*DelAllPinMsgReq) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{6}
}

func (x *DelAllPinMsgReq) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

type DelPinMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
}

func (x *DelPinMsgResp) Reset() {
	*x = DelPinMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPinMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPinMsgResp) ProtoMessage() {}

func (x *DelPinMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPinMsgResp.ProtoReflect.Descriptor instead.
func (*DelPinMsgResp) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{7}
}

func (x *DelPinMsgResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type BotCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command     string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`         //命令
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` //描述
}

func (x *BotCommand) Reset() {
	*x = BotCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCommand) ProtoMessage() {}

func (x *BotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCommand.ProtoReflect.Descriptor instead.
func (*BotCommand) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{8}
}

func (x *BotCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *BotCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SendBotCommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotCommand []*BotCommand `protobuf:"bytes,1,rep,name=botCommand,proto3" json:"botCommand,omitempty"`
}

func (x *SendBotCommandReq) Reset() {
	*x = SendBotCommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandReq) ProtoMessage() {}

func (x *SendBotCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandReq.ProtoReflect.Descriptor instead.
func (*SendBotCommandReq) Descriptor() ([]byte, []int) {
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP(), []int{9}
}

func (x *SendBotCommandReq) GetBotCommand() []*BotCommand {
	if x != nil {
		return x.BotCommand
	}
	return nil
}

var File_app_tgbot_rpc_proto_tgbot_proto protoreflect.FileDescriptor

var file_app_tgbot_rpc_proto_tgbot_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x67, 0x62, 0x6f, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x67, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f,
	0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x2a, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x12, 0x20, 0x0a, 0x06,
	0x6d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x22, 0xb4,
	0x01, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0b, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x52, 0x0b, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x73, 0x50,
	0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x50, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x50, 0x69, 0x6e, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x41, 0x6c, 0x6c, 0x50, 0x69, 0x6e,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x22, 0x2d,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x50, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x48, 0x0a,
	0x0a, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x0a,
	0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x0a, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0xa5, 0x02, 0x0a,
	0x05, 0x74, 0x67, 0x62, 0x6f, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f,
	0x74, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f,
	0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x42, 0x6f, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x50, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x6c, 0x50, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x41, 0x6c, 0x6c, 0x50, 0x69, 0x6e, 0x4d, 0x73, 0x67,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x6c, 0x6c, 0x50, 0x69, 0x6e, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x69,
	0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64,
	0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x69, 0x6e, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_tgbot_rpc_proto_tgbot_proto_rawDescOnce sync.Once
	file_app_tgbot_rpc_proto_tgbot_proto_rawDescData = file_app_tgbot_rpc_proto_tgbot_proto_rawDesc
)

func file_app_tgbot_rpc_proto_tgbot_proto_rawDescGZIP() []byte {
	file_app_tgbot_rpc_proto_tgbot_proto_rawDescOnce.Do(func() {
		file_app_tgbot_rpc_proto_tgbot_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_tgbot_rpc_proto_tgbot_proto_rawDescData)
	})
	return file_app_tgbot_rpc_proto_tgbot_proto_rawDescData
}

var file_app_tgbot_rpc_proto_tgbot_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_tgbot_rpc_proto_tgbot_proto_goTypes = []interface{}{
	(*SendBotMsgRequest)(nil),  // 0: pb.SendBotMsgRequest
	(*SendBotMsgResponse)(nil), // 1: pb.SendBotMsgResponse
	(*Item)(nil),               // 2: pb.Item
	(*Markup)(nil),             // 3: pb.Markup
	(*SendPhotoRequest)(nil),   // 4: pb.SendPhotoRequest
	(*DelPinMsgReq)(nil),       // 5: pb.DelPinMsgReq
	(*DelAllPinMsgReq)(nil),    // 6: pb.DelAllPinMsgReq
	(*DelPinMsgResp)(nil),      // 7: pb.DelPinMsgResp
	(*BotCommand)(nil),         // 8: pb.BotCommand
	(*SendBotCommandReq)(nil),  // 9: pb.SendBotCommandReq
}
var file_app_tgbot_rpc_proto_tgbot_proto_depIdxs = []int32{
	2, // 0: pb.Markup.markup:type_name -> pb.Item
	3, // 1: pb.SendPhotoRequest.replyMarkup:type_name -> pb.Markup
	8, // 2: pb.SendBotCommandReq.botCommand:type_name -> pb.BotCommand
	0, // 3: pb.tgbot.SendBotMsg:input_type -> pb.SendBotMsgRequest
	4, // 4: pb.tgbot.SendPhoto:input_type -> pb.SendPhotoRequest
	5, // 5: pb.tgbot.DelPinMsg:input_type -> pb.DelPinMsgReq
	6, // 6: pb.tgbot.DelAllPinMsg:input_type -> pb.DelAllPinMsgReq
	9, // 7: pb.tgbot.SendBotCommand:input_type -> pb.SendBotCommandReq
	1, // 8: pb.tgbot.SendBotMsg:output_type -> pb.SendBotMsgResponse
	1, // 9: pb.tgbot.SendPhoto:output_type -> pb.SendBotMsgResponse
	7, // 10: pb.tgbot.DelPinMsg:output_type -> pb.DelPinMsgResp
	7, // 11: pb.tgbot.DelAllPinMsg:output_type -> pb.DelPinMsgResp
	7, // 12: pb.tgbot.SendBotCommand:output_type -> pb.DelPinMsgResp
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_tgbot_rpc_proto_tgbot_proto_init() }
func file_app_tgbot_rpc_proto_tgbot_proto_init() {
	if File_app_tgbot_rpc_proto_tgbot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Markup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPinMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelAllPinMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPinMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tgbot_rpc_proto_tgbot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_tgbot_rpc_proto_tgbot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_tgbot_rpc_proto_tgbot_proto_goTypes,
		DependencyIndexes: file_app_tgbot_rpc_proto_tgbot_proto_depIdxs,
		MessageInfos:      file_app_tgbot_rpc_proto_tgbot_proto_msgTypes,
	}.Build()
	File_app_tgbot_rpc_proto_tgbot_proto = out.File
	file_app_tgbot_rpc_proto_tgbot_proto_rawDesc = nil
	file_app_tgbot_rpc_proto_tgbot_proto_goTypes = nil
	file_app_tgbot_rpc_proto_tgbot_proto_depIdxs = nil
}
