// Code generated by goctl. DO NOT EDIT.
package types

type VideoListReq struct {
	Titel string `form:"titel,optional"`
	Page  int64  `form:"page"`
	Size  int64  `form:"size"`
}

type Video struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Desc        string `json:"desc"`
	FilePath    string `json:"file_path"`
	CreatedTime int64  `json:"created_time"`
	Avatar      string `json:"avatar"`
}

type VideoListResp struct {
	List  []*Video `json:"list"`
	Total int64    `json:"total"`
}

type Response struct {
}

type LabelListReq struct {
	Vid  int64 `form:"vid"`
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type Label struct {
	Lid         string `json:"lid"`
	LabelUserId string `json:"label_user_id"`
	Vid         int64  `json:"vid"`
	Uid         int64  `json:"uid"`
	Title       string `json:"title"`
	Likes       bool   `json:"likes"`
	NoLikes     bool   `json:"no_likes"`
	LikesNum    int64  `json:"likes_num"`
	NoLikesNum  int64  `json:"no_likes_num"`
	CreatedTime int64  `json:"created_time"`
}

type LabelListResp struct {
	List  []*Label `json:"list"`
	Total int64    `json:"total"`
}

type LabelAddReq struct {
	Vid   int64  `json:"vid"`
	Title string `json:"title"`
}

type LabelAddResp struct {
	Repeat bool `json:"repeat"`
}

type LabelUserLikeReq struct {
	LabelUserId string `json:"label_user_id,optional"`
	Lid         string `json:"lid"`
	Likes       bool   `json:"likes,optional"`    // 1:点赞，0：取消点赞
	NoLikes     bool   `json:"no_likes,optional"` // 1：点踩，0：取消点踩
}

type LabelUserLikeResp struct {
	Lid         string `json:"lid"`
	LabelUserId string `json:"label_user_id"`
	Vid         int64  `json:"vid"`
	Uid         int64  `json:"uid"`
	Title       string `json:"title"`
	Likes       bool   `json:"likes"`
	NoLikes     bool   `json:"no_likes"`
	LikesNum    int64  `json:"likes_num"`
	NoLikesNum  int64  `json:"no_likes_num"`
	CreatedTime int64  `json:"created_time"`
}

type CommentListReq struct {
	Vid  int64 `form:"vid"`
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type CommentListResp struct {
	List  []*VideoComment `json:"list"`
	Total int64           `json:"total"`
}

type VideoComment struct {
	Id          string `json:"id"`
	Content     string `json:"content"`
	UserName    string `json:"user_name"`
	Avatar      string `json:"avatar"`
	Uid         int64  `json:"uid"`
	Vid         int64  `json:"vid"`
	CreatedTime int64  `json:"created_time"`
	ReplyCount  int64  `json:"reply_count"`
}

type CommentAddReq struct {
	Content string `json:"content"`
	Vid     int64  `json:"vid"`
}

type ReplyListReq struct {
	Commentid string `form:"comment_id"`
	Page      int64  `form:"page"`
	Size      int64  `form:"size"`
}

type ReplyListResp struct {
	List  []*VideoReply `json:"list"`
	Total int64         `json:"total"`
}

type VideoReply struct {
	Id             string `json:"id"`
	CommentId      string `json:"comment_id"`
	Content        string `json:"content"`
	CreatedTime    int64  `json:"created_time"`
	FromUserId     int64  `json:"from_user_id"`
	FromUserName   string `json:"from_user_name"`
	FromUserAvatar string `json:"from_user_avatar"`
	ToUserId       int64  `json:"to_user_id"`
	ToUserName     string `json:"to_user_name"`
	ToUserAvatar   string `json:"to_user_avatar"`
}

type ReplyAddReq struct {
	CommentId  string `json:"comment_id"`
	Content    string `json:"content"`
	FromUserId int64  `json:"from_user_id"`
}
