// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	resource "T-driver/app/resource/api/internal/handler/resource"
	"T-driver/app/resource/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 云下载
					Method:  http.MethodPost,
					Path:    "/cloudDownload",
					Handler: resource.CloudDownloadHandler(serverCtx),
				},
				{
					// 链接上传文件
					Method:  http.MethodPost,
					Path:    "/cloudLink",
					Handler: resource.CloudLinkHandler(serverCtx),
				},
				{
					// 本地上传文件
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: resource.UploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/resource"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// titan资源链接转发
				Method:  http.MethodGet,
				Path:    "/relay",
				Handler: resource.RelayTitanHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/resource"),
	)
}
