// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: app/video/rpc/videoProto/video.proto

package videoPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVideoListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Page   int64   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size   int64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Desc   string  `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Status int64   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Ids    []int64 `protobuf:"varint,6,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetVideoListReq) Reset() {
	*x = GetVideoListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListReq) ProtoMessage() {}

func (x *GetVideoListReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListReq.ProtoReflect.Descriptor instead.
func (*GetVideoListReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoListReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetVideoListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetVideoListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetVideoListReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetVideoListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetVideoListReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid         int64  `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc        string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	FilePath    string `protobuf:"bytes,4,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Status      int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` //状态 1禁用2进行中3完成4失败
	CreatedTime int64  `protobuf:"varint,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime int64  `protobuf:"varint,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	Url         string `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty"`
	Cid         string `protobuf:"bytes,9,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{1}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Video) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Video) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Video) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *Video) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type VideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{2}
}

type GetVideoListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoList []*Video `protobuf:"bytes,1,rep,name=videoList,proto3" json:"videoList,omitempty"`
	Total     int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetVideoListResp) Reset() {
	*x = GetVideoListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListResp) ProtoMessage() {}

func (x *GetVideoListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListResp.ProtoReflect.Descriptor instead.
func (*GetVideoListResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoListResp) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *GetVideoListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc     string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Filename string `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Status   int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` //状态 1禁用2进行中3完成4失败
}

func (x *CreateVideoReq) Reset() {
	*x = CreateVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoReq) ProtoMessage() {}

func (x *CreateVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoReq.ProtoReflect.Descriptor instead.
func (*CreateVideoReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVideoReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateVideoReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateVideoReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateVideoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateVideoResp) Reset() {
	*x = CreateVideoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoResp) ProtoMessage() {}

func (x *CreateVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoResp.ProtoReflect.Descriptor instead.
func (*CreateVideoResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVideoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteVideoReq) Reset() {
	*x = DeleteVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoReq) ProtoMessage() {}

func (x *DeleteVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoReq.ProtoReflect.Descriptor instead.
func (*DeleteVideoReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVideoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc     string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	FilePath string `protobuf:"bytes,4,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Cid      string `protobuf:"bytes,5,opt,name=cid,proto3" json:"cid,omitempty"`
	Url      string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Status   int64  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` //状态 1禁用2进行中3完成4失败
}

func (x *UpdateVideoReq) Reset() {
	*x = UpdateVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoReq) ProtoMessage() {}

func (x *UpdateVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoReq.ProtoReflect.Descriptor instead.
func (*UpdateVideoReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVideoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateVideoReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UpdateVideoReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *UpdateVideoReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateVideoReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Vid   int64  `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
	Uid   int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CreateLabelReq) Reset() {
	*x = CreateLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelReq) ProtoMessage() {}

func (x *CreateLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelReq.ProtoReflect.Descriptor instead.
func (*CreateLabelReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLabelReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLabelReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *CreateLabelReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetLabelListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid  int64  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Page int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Id   string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLabelListReq) Reset() {
	*x = GetLabelListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabelListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelListReq) ProtoMessage() {}

func (x *GetLabelListReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelListReq.ProtoReflect.Descriptor instead.
func (*GetLabelListReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetLabelListReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *GetLabelListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLabelListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetLabelListReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VideosLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vid         int64  `protobuf:"varint,3,opt,name=vid,proto3" json:"vid,omitempty"`
	CreatedTime int64  `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Uid         int64  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *VideosLabel) Reset() {
	*x = VideosLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideosLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideosLabel) ProtoMessage() {}

func (x *VideosLabel) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideosLabel.ProtoReflect.Descriptor instead.
func (*VideosLabel) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{10}
}

func (x *VideosLabel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideosLabel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideosLabel) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VideosLabel) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *VideosLabel) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetLabelListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*VideosLabel `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetLabelListResp) Reset() {
	*x = GetLabelListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabelListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelListResp) ProtoMessage() {}

func (x *GetLabelListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelListResp.ProtoReflect.Descriptor instead.
func (*GetLabelListResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{11}
}

func (x *GetLabelListResp) GetList() []*VideosLabel {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetLabelListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SaveLabelUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lid     string `protobuf:"bytes,2,opt,name=lid,proto3" json:"lid,omitempty"`          //标签id
	Uid     int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`         //用户id
	Likes   bool   `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`     //点赞
	NoLikes bool   `protobuf:"varint,5,opt,name=noLikes,proto3" json:"noLikes,omitempty"` //点踩
}

func (x *SaveLabelUserReq) Reset() {
	*x = SaveLabelUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLabelUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLabelUserReq) ProtoMessage() {}

func (x *SaveLabelUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLabelUserReq.ProtoReflect.Descriptor instead.
func (*SaveLabelUserReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{12}
}

func (x *SaveLabelUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveLabelUserReq) GetLid() string {
	if x != nil {
		return x.Lid
	}
	return ""
}

func (x *SaveLabelUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SaveLabelUserReq) GetLikes() bool {
	if x != nil {
		return x.Likes
	}
	return false
}

func (x *SaveLabelUserReq) GetNoLikes() bool {
	if x != nil {
		return x.NoLikes
	}
	return false
}

type GetLabelUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lid []string `protobuf:"bytes,1,rep,name=lid,proto3" json:"lid,omitempty"`
	Uid int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Id  string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLabelUserReq) Reset() {
	*x = GetLabelUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabelUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelUserReq) ProtoMessage() {}

func (x *GetLabelUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelUserReq.ProtoReflect.Descriptor instead.
func (*GetLabelUserReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{13}
}

func (x *GetLabelUserReq) GetLid() []string {
	if x != nil {
		return x.Lid
	}
	return nil
}

func (x *GetLabelUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetLabelUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VideosLabelUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lid         string `protobuf:"bytes,2,opt,name=lid,proto3" json:"lid,omitempty"`
	Uid         int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Likes       bool   `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
	NoLikes     bool   `protobuf:"varint,5,opt,name=noLikes,proto3" json:"noLikes,omitempty"`
	CreatedTime int64  `protobuf:"varint,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
}

func (x *VideosLabelUser) Reset() {
	*x = VideosLabelUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideosLabelUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideosLabelUser) ProtoMessage() {}

func (x *VideosLabelUser) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideosLabelUser.ProtoReflect.Descriptor instead.
func (*VideosLabelUser) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{14}
}

func (x *VideosLabelUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideosLabelUser) GetLid() string {
	if x != nil {
		return x.Lid
	}
	return ""
}

func (x *VideosLabelUser) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *VideosLabelUser) GetLikes() bool {
	if x != nil {
		return x.Likes
	}
	return false
}

func (x *VideosLabelUser) GetNoLikes() bool {
	if x != nil {
		return x.NoLikes
	}
	return false
}

func (x *VideosLabelUser) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type GetLabelUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*VideosLabelUser `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetLabelUserResp) Reset() {
	*x = GetLabelUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabelUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelUserResp) ProtoMessage() {}

func (x *GetLabelUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelUserResp.ProtoReflect.Descriptor instead.
func (*GetLabelUserResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{15}
}

func (x *GetLabelUserResp) GetList() []*VideosLabelUser {
	if x != nil {
		return x.List
	}
	return nil
}

type CountLabelUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lid []string `protobuf:"bytes,1,rep,name=lid,proto3" json:"lid,omitempty"`
}

func (x *CountLabelUserReq) Reset() {
	*x = CountLabelUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountLabelUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLabelUserReq) ProtoMessage() {}

func (x *CountLabelUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLabelUserReq.ProtoReflect.Descriptor instead.
func (*CountLabelUserReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{16}
}

func (x *CountLabelUserReq) GetLid() []string {
	if x != nil {
		return x.Lid
	}
	return nil
}

type CountLabelUserItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lid        string `protobuf:"bytes,1,opt,name=lid,proto3" json:"lid,omitempty"`
	LikesNum   int64  `protobuf:"varint,2,opt,name=likesNum,proto3" json:"likesNum,omitempty"`
	NoLikesNum int64  `protobuf:"varint,3,opt,name=noLikesNum,proto3" json:"noLikesNum,omitempty"`
}

func (x *CountLabelUserItem) Reset() {
	*x = CountLabelUserItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountLabelUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLabelUserItem) ProtoMessage() {}

func (x *CountLabelUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLabelUserItem.ProtoReflect.Descriptor instead.
func (*CountLabelUserItem) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{17}
}

func (x *CountLabelUserItem) GetLid() string {
	if x != nil {
		return x.Lid
	}
	return ""
}

func (x *CountLabelUserItem) GetLikesNum() int64 {
	if x != nil {
		return x.LikesNum
	}
	return 0
}

func (x *CountLabelUserItem) GetNoLikesNum() int64 {
	if x != nil {
		return x.NoLikesNum
	}
	return 0
}

type CountLabelUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*CountLabelUserItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *CountLabelUserResp) Reset() {
	*x = CountLabelUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountLabelUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLabelUserResp) ProtoMessage() {}

func (x *CountLabelUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLabelUserResp.ProtoReflect.Descriptor instead.
func (*CountLabelUserResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{18}
}

func (x *CountLabelUserResp) GetList() []*CountLabelUserItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid     int64  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Uid     int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCommentReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *CreateCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetCommentListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid  int64 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Page int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Uid  int64 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetCommentListReq) Reset() {
	*x = GetCommentListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListReq) ProtoMessage() {}

func (x *GetCommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListReq.ProtoReflect.Descriptor instead.
func (*GetCommentListReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{20}
}

func (x *GetCommentListReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *GetCommentListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetCommentListReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type VideosComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vid         int64  `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
	Uid         int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Content     string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedTime int64  `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	ReplyCount  int64  `protobuf:"varint,6,opt,name=ReplyCount,proto3" json:"ReplyCount,omitempty"`
}

func (x *VideosComment) Reset() {
	*x = VideosComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideosComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideosComment) ProtoMessage() {}

func (x *VideosComment) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideosComment.ProtoReflect.Descriptor instead.
func (*VideosComment) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{21}
}

func (x *VideosComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideosComment) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VideosComment) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *VideosComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VideosComment) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *VideosComment) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type GetCommentListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*VideosComment `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetCommentListResp) Reset() {
	*x = GetCommentListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListResp) ProtoMessage() {}

func (x *GetCommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListResp.ProtoReflect.Descriptor instead.
func (*GetCommentListResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{22}
}

func (x *GetCommentListResp) GetList() []*VideosComment {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetCommentListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid        int64  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	ToUserId   int64  `protobuf:"varint,2,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CommentId  string `protobuf:"bytes,4,opt,name=commentId,proto3" json:"commentId,omitempty"`
	FromUserId int64  `protobuf:"varint,5,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
}

func (x *CreateReplyReq) Reset() {
	*x = CreateReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyReq) ProtoMessage() {}

func (x *CreateReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyReq.ProtoReflect.Descriptor instead.
func (*CreateReplyReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{23}
}

func (x *CreateReplyReq) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *CreateReplyReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *CreateReplyReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReplyReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *CreateReplyReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

type CreateReplyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedTime int64  `protobuf:"varint,2,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	ToUserId    int64  `protobuf:"varint,3,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Content     string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CommentId   string `protobuf:"bytes,5,opt,name=commentId,proto3" json:"commentId,omitempty"`
	FromUserId  int64  `protobuf:"varint,6,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
}

func (x *CreateReplyResp) Reset() {
	*x = CreateReplyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResp) ProtoMessage() {}

func (x *CreateReplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResp.ProtoReflect.Descriptor instead.
func (*CreateReplyResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{24}
}

func (x *CreateReplyResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateReplyResp) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *CreateReplyResp) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *CreateReplyResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReplyResp) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *CreateReplyResp) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

type GetReplyListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId string `protobuf:"bytes,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	Page      int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size      int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ToUserid  int64  `protobuf:"varint,4,opt,name=toUserid,proto3" json:"toUserid,omitempty"`
}

func (x *GetReplyListReq) Reset() {
	*x = GetReplyListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyListReq) ProtoMessage() {}

func (x *GetReplyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyListReq.ProtoReflect.Descriptor instead.
func (*GetReplyListReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{25}
}

func (x *GetReplyListReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *GetReplyListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetReplyListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetReplyListReq) GetToUserid() int64 {
	if x != nil {
		return x.ToUserid
	}
	return 0
}

type VideosReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToUserId    int64  `protobuf:"varint,3,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Content     string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CommentId   string `protobuf:"bytes,5,opt,name=commentId,proto3" json:"commentId,omitempty"`
	FromUserId  int64  `protobuf:"varint,6,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	CreatedTime int64  `protobuf:"varint,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
}

func (x *VideosReply) Reset() {
	*x = VideosReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideosReply) ProtoMessage() {}

func (x *VideosReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideosReply.ProtoReflect.Descriptor instead.
func (*VideosReply) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{26}
}

func (x *VideosReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideosReply) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *VideosReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VideosReply) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *VideosReply) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *VideosReply) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type GetReplyListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*VideosReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetReplyListResp) Reset() {
	*x = GetReplyListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyListResp) ProtoMessage() {}

func (x *GetReplyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyListResp.ProtoReflect.Descriptor instead.
func (*GetReplyListResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{27}
}

func (x *GetReplyListResp) GetList() []*VideosReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetReplyListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SaveLabelUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveLabelUserResp) Reset() {
	*x = SaveLabelUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLabelUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLabelUserResp) ProtoMessage() {}

func (x *SaveLabelUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLabelUserResp.ProtoReflect.Descriptor instead.
func (*SaveLabelUserResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{28}
}

func (x *SaveLabelUserResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOneLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOneLabelReq) Reset() {
	*x = GetOneLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLabelReq) ProtoMessage() {}

func (x *GetOneLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLabelReq.ProtoReflect.Descriptor instead.
func (*GetOneLabelReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{29}
}

func (x *GetOneLabelReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOneLabelUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOneLabelUserReq) Reset() {
	*x = GetOneLabelUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLabelUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLabelUserReq) ProtoMessage() {}

func (x *GetOneLabelUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLabelUserReq.ProtoReflect.Descriptor instead.
func (*GetOneLabelUserReq) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{30}
}

func (x *GetOneLabelUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateLabelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repeat bool `protobuf:"varint,1,opt,name=repeat,proto3" json:"repeat,omitempty"`
}

func (x *CreateLabelResp) Reset() {
	*x = CreateLabelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelResp) ProtoMessage() {}

func (x *CreateLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_videoProto_video_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelResp.ProtoReflect.Descriptor instead.
func (*CreateLabelResp) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_videoProto_video_proto_rawDescGZIP(), []int{31}
}

func (x *CreateLabelResp) GetRepeat() bool {
	if x != nil {
		return x.Repeat
	}
	return false
}

var File_app_video_rpc_videoProto_video_proto protoreflect.FileDescriptor

var file_app_video_rpc_videoProto_video_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x8d, 0x01, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x05, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x51, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x27, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x80, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4a, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x79, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x76, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6c, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6e, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x97, 0x01, 0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6c, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6e, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6e, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x69, 0x64, 0x22, 0x62, 0x0a,
	0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6c, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x4e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x4e, 0x75,
	0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x4e, 0x75,
	0x6d, 0x22, 0x40, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x96, 0x01, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x73,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x23, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x32, 0xf5, 0x06, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x36, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x34, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x39, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x3c, 0x0a, 0x0d, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_video_rpc_videoProto_video_proto_rawDescOnce sync.Once
	file_app_video_rpc_videoProto_video_proto_rawDescData = file_app_video_rpc_videoProto_video_proto_rawDesc
)

func file_app_video_rpc_videoProto_video_proto_rawDescGZIP() []byte {
	file_app_video_rpc_videoProto_video_proto_rawDescOnce.Do(func() {
		file_app_video_rpc_videoProto_video_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_video_rpc_videoProto_video_proto_rawDescData)
	})
	return file_app_video_rpc_videoProto_video_proto_rawDescData
}

var file_app_video_rpc_videoProto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_app_video_rpc_videoProto_video_proto_goTypes = []interface{}{
	(*GetVideoListReq)(nil),    // 0: pb.GetVideoListReq
	(*Video)(nil),              // 1: pb.Video
	(*VideoResponse)(nil),      // 2: pb.VideoResponse
	(*GetVideoListResp)(nil),   // 3: pb.GetVideoListResp
	(*CreateVideoReq)(nil),     // 4: pb.CreateVideoReq
	(*CreateVideoResp)(nil),    // 5: pb.CreateVideoResp
	(*DeleteVideoReq)(nil),     // 6: pb.DeleteVideoReq
	(*UpdateVideoReq)(nil),     // 7: pb.UpdateVideoReq
	(*CreateLabelReq)(nil),     // 8: pb.CreateLabelReq
	(*GetLabelListReq)(nil),    // 9: pb.GetLabelListReq
	(*VideosLabel)(nil),        // 10: pb.VideosLabel
	(*GetLabelListResp)(nil),   // 11: pb.GetLabelListResp
	(*SaveLabelUserReq)(nil),   // 12: pb.SaveLabelUserReq
	(*GetLabelUserReq)(nil),    // 13: pb.GetLabelUserReq
	(*VideosLabelUser)(nil),    // 14: pb.VideosLabelUser
	(*GetLabelUserResp)(nil),   // 15: pb.GetLabelUserResp
	(*CountLabelUserReq)(nil),  // 16: pb.CountLabelUserReq
	(*CountLabelUserItem)(nil), // 17: pb.CountLabelUserItem
	(*CountLabelUserResp)(nil), // 18: pb.CountLabelUserResp
	(*CreateCommentReq)(nil),   // 19: pb.CreateCommentReq
	(*GetCommentListReq)(nil),  // 20: pb.GetCommentListReq
	(*VideosComment)(nil),      // 21: pb.VideosComment
	(*GetCommentListResp)(nil), // 22: pb.GetCommentListResp
	(*CreateReplyReq)(nil),     // 23: pb.CreateReplyReq
	(*CreateReplyResp)(nil),    // 24: pb.CreateReplyResp
	(*GetReplyListReq)(nil),    // 25: pb.GetReplyListReq
	(*VideosReply)(nil),        // 26: pb.VideosReply
	(*GetReplyListResp)(nil),   // 27: pb.GetReplyListResp
	(*SaveLabelUserResp)(nil),  // 28: pb.SaveLabelUserResp
	(*GetOneLabelReq)(nil),     // 29: pb.GetOneLabelReq
	(*GetOneLabelUserReq)(nil), // 30: pb.GetOneLabelUserReq
	(*CreateLabelResp)(nil),    // 31: pb.CreateLabelResp
}
var file_app_video_rpc_videoProto_video_proto_depIdxs = []int32{
	1,  // 0: pb.GetVideoListResp.videoList:type_name -> pb.Video
	10, // 1: pb.GetLabelListResp.list:type_name -> pb.VideosLabel
	14, // 2: pb.GetLabelUserResp.list:type_name -> pb.VideosLabelUser
	17, // 3: pb.CountLabelUserResp.list:type_name -> pb.CountLabelUserItem
	21, // 4: pb.GetCommentListResp.list:type_name -> pb.VideosComment
	26, // 5: pb.GetReplyListResp.list:type_name -> pb.VideosReply
	4,  // 6: pb.video.CreateVideo:input_type -> pb.CreateVideoReq
	7,  // 7: pb.video.UpdateVideo:input_type -> pb.UpdateVideoReq
	6,  // 8: pb.video.DeleteVideo:input_type -> pb.DeleteVideoReq
	0,  // 9: pb.video.GetVideoList:input_type -> pb.GetVideoListReq
	8,  // 10: pb.video.CreateLabel:input_type -> pb.CreateLabelReq
	9,  // 11: pb.video.GetLabelList:input_type -> pb.GetLabelListReq
	29, // 12: pb.video.GetOneLabel:input_type -> pb.GetOneLabelReq
	12, // 13: pb.video.SaveLabelUser:input_type -> pb.SaveLabelUserReq
	13, // 14: pb.video.GetLabelUser:input_type -> pb.GetLabelUserReq
	30, // 15: pb.video.GetOneLabelUser:input_type -> pb.GetOneLabelUserReq
	16, // 16: pb.video.CountLabelUser:input_type -> pb.CountLabelUserReq
	19, // 17: pb.video.CreateComment:input_type -> pb.CreateCommentReq
	20, // 18: pb.video.GetCommentList:input_type -> pb.GetCommentListReq
	23, // 19: pb.video.CreateReply:input_type -> pb.CreateReplyReq
	25, // 20: pb.video.GetReplyList:input_type -> pb.GetReplyListReq
	5,  // 21: pb.video.CreateVideo:output_type -> pb.CreateVideoResp
	2,  // 22: pb.video.UpdateVideo:output_type -> pb.VideoResponse
	2,  // 23: pb.video.DeleteVideo:output_type -> pb.VideoResponse
	3,  // 24: pb.video.GetVideoList:output_type -> pb.GetVideoListResp
	31, // 25: pb.video.CreateLabel:output_type -> pb.CreateLabelResp
	11, // 26: pb.video.GetLabelList:output_type -> pb.GetLabelListResp
	10, // 27: pb.video.GetOneLabel:output_type -> pb.VideosLabel
	28, // 28: pb.video.SaveLabelUser:output_type -> pb.SaveLabelUserResp
	15, // 29: pb.video.GetLabelUser:output_type -> pb.GetLabelUserResp
	14, // 30: pb.video.GetOneLabelUser:output_type -> pb.VideosLabelUser
	18, // 31: pb.video.CountLabelUser:output_type -> pb.CountLabelUserResp
	2,  // 32: pb.video.CreateComment:output_type -> pb.VideoResponse
	22, // 33: pb.video.GetCommentList:output_type -> pb.GetCommentListResp
	24, // 34: pb.video.CreateReply:output_type -> pb.CreateReplyResp
	27, // 35: pb.video.GetReplyList:output_type -> pb.GetReplyListResp
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_video_rpc_videoProto_video_proto_init() }
func file_app_video_rpc_videoProto_video_proto_init() {
	if File_app_video_rpc_videoProto_video_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_video_rpc_videoProto_video_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVideoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabelListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideosLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabelListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLabelUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabelUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideosLabelUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabelUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountLabelUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountLabelUserItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountLabelUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideosComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideosReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLabelUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLabelUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_video_rpc_videoProto_video_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLabelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_video_rpc_videoProto_video_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_video_rpc_videoProto_video_proto_goTypes,
		DependencyIndexes: file_app_video_rpc_videoProto_video_proto_depIdxs,
		MessageInfos:      file_app_video_rpc_videoProto_video_proto_msgTypes,
	}.Build()
	File_app_video_rpc_videoProto_video_proto = out.File
	file_app_video_rpc_videoProto_video_proto_rawDesc = nil
	file_app_video_rpc_videoProto_video_proto_goTypes = nil
	file_app_video_rpc_videoProto_video_proto_depIdxs = nil
}
