// Code generated by goctl. DO NOT EDIT.
package types

type AirdropTokenDetail struct {
	BookableToken int64 `json:"bookable_token"`
	BookedToken   int64 `json:"booked_token"`
}

type AssetFile struct {
	Id          string   `json:"id"`           //id
	AssetId     int64    `json:"asset_id"`     //资源id
	Uid         int64    `json:"uid"`          //uid
	Cid         string   `json:"cid"`          //资源id
	AssetName   string   `json:"asset_name"`   //资源名称
	AssetSize   int64    `json:"asset_size"`   //资源大小
	AssetType   int64    `json:"asset_type"`   //1文件夹2文件3视频4图片
	Completion  int64    `json:"completion"`   //完成度
	Source      int64    `json:"source"`       //来源 1TDriver2云上传3Telegram
	Status      int64    `json:"status"`       //状态 1禁用2进行中3完成4失败5空间不足
	CreatedTime int64    `json:"created_time"` //上传时间
	IsTag       int64    `json:"is_tag"`       //是否标记
	Url         string   `json:"url"`          //链接
	UploadErr   string   `json:"upload_err"`   //上传失败原因
	IsDelete    int64    `json:"is_delete"`    //是否删除
	ImgBase64   string   `json:"img_base64"`   //图片base64
	UrlList     []string `json:"url_list"`     //文件链接
}

type AssetItem struct {
	Id          int64    `json:"id"`           //id
	AssetID     int64    `json:"asset_id"`     //asset_id
	Uid         int64    `json:"uid"`          //用户id
	Cid         string   `json:"cid"`          //资源id
	Url         string   `json:"url"`          //链接
	TransitType int64    `json:"transit_type"` //上传类型 1上传文件夹2上传文件3云链接 4TG 5X 6TK 7种子
	AssetName   string   `json:"asset_name"`   //资源名称
	AssetSize   int64    `json:"asset_size"`   //资源大小
	AssetType   int64    `json:"asset_type"`   //1文件夹2文件3视频4图片
	CreatedTime int64    `json:"created_time"` //上传时间
	Pid         int64    `json:"pid"`          //文件目录
	Pname       string   `json:"pname"`        //文件目录名称
	UpdatedTime int64    `json:"updated_time"` //修改时间
	DeletedDay  int      `json:"deleted_day"`  //多少天后删除
	IsTag       int64    `json:"is_tag"`       //是否标记
	Source      int64    `json:"source"`       //来源 1TDriver2云上传3Telegram
	Status      int64    `json:"status"`       //状态 1禁用2进行中3完成4失败
	IsReport    int64    `json:"is_report"`    //是否举报 1是2否
	ErrTip      string   `json:"err_tip"`      //错误提示
	IsDefault   int64    `json:"is_default"`   //是否默认 1是0否
	IsDelete    int64    `json:"is_delete"`    //是否删除 1是 0否
	ImgBase64   string   `json:"img_base64"`   //图片base64
	UrlList     []string `json:"url_list"`     //文件链接
}

type DictItem struct {
	Id          int64  `json:"id"`           //id
	ParamType   int64  `json:"parm_type"`    //类型 1注册奖励 2引荐奖励 3活动规则 4其他设置
	Name        string `json:"name"`         //字典名称
	Code        string `json:"code"`         //code
	Value       string `json:"value"`        //积分
	BackupValue int64  `json:"backup_value"` //多少G空间
	Status      bool   `json:"status"`       //状态 0未完成 1完成
}

type ExChangeTokenReq struct {
	Storage int64 `json:"storage"`
}

type Friend struct {
	Uid          int64  `json:"uid"`           //用户id
	Name         string `json:"name"`          //用户名
	Points       int64  `json:"points"`        //积分
	RewardPoints int64  `json:"reward_points"` //奖励积分
	CreatedTime  int64  `json:"created_time"`  //引荐时间
}

type GuideResponse struct {
	IsReceive bool `json:"is_receive"`
}

type InTransit struct {
	Id          int64  `json:"id"`           //id
	Uid         int64  `json:"uid"`          //uid
	Cid         string `json:"cid"`          //资源id
	TransitType int64  `json:"transit_type"` //上传类型 1上传文件夹2上传文件3云链接 4TG 5X 6TK 7种子
	AssetName   string `json:"asset_name"`   //资源名称
	AssetSize   int64  `json:"asset_size"`   //资源大小
	AssetType   int64  `json:"asset_type"`   //1文件夹2文件3视频4图片
	Completion  int64  `json:"completion"`   //完成度
	Source      int64  `json:"source"`       //来源 1TDriver2云上传3Telegram
	Status      int64  `json:"status"`       //状态 1禁用2进行中3完成4失败5空间不足
	CreatedTime int64  `json:"created_time"` //上传时间
	IsTag       int64  `json:"is_tag"`       //是否标记
	Url         string `json:"url"`          //链接
	UploadErr   string `json:"upload_err"`   //上传失败原因
}

type LoginResp struct {
	IsNew      bool   `json:"is_new"`      //是否新用户
	TitanToken string `json:"titan_token"` //titan token
	Exp        int64  `json:"exp"`         //有效期
}

type MessageItem struct {
	Id          int64  `json:"id"`
	Uid         int64  `json:"uid"`    //用户id
	Name        string `json:"name"`   //用户名
	Puid        int64  `json:"puid"`   //绑定用户的uid
	Remark      string `json:"remark"` //备注
	Status      int64  `json:"status"` //状态 1进行中2已完成3拒绝绑定
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type MsgResponse struct {
	Status bool   `json:"status"`
	Msg    string `json:"msg"`
}

type Racking struct {
	Uid      int64  `json:"uid"`
	Name     string `json:"name"`     //用户名
	Serial   int64  `json:"serial"`   //序号
	Integral int64  `json:"integral"` //积分
}

type Request struct {
}

type Response struct {
}

type Reward struct {
	Uid         int64  `json:"uid"`          //用户id
	Name        string `json:"name"`         //用户名
	Source      int64  `json:"source"`       //来源
	CreatedTime int64  `json:"created_time"` //引荐时间
}

type SetLanguageReq struct {
	LanguageCode string `json:"language_code"` //语言代码 zh和en
}

type Share struct {
	Id          int64   `json:"id"`
	UId         int64   `json:"uid"`
	AssetIds    []int64 `json:"asset_ids"`    //资源ids
	AssetName   string  `json:"asset_name"`   //文件名
	AssetSize   int64   `json:"asset_size"`   //文件大小
	AssetType   int64   `json:"asset_type"`   //2文件3视频4图片
	Link        string  `json:"link"`         //链接
	Status      int64   `json:"status"`       //有效期状态 0永久有效 1已失效 2快到期
	IsPass      bool    `json:"is_pass"`      //是否有密码
	Day         int     `json:"day"`          //剩余多少天到期
	ReadNum     int64   `json:"read_num"`     //阅览数量
	SaveNum     int64   `json:"save_num"`     //保存数量
	CreatedTime int64   `json:"created_time"` //创建时间
}

type SpaceItem struct {
	Id              int64 `json:"id"`
	Uid             int64 `json:"uid"`
	StorageExchange int64 `json:"storage_exchange"`
	CreatedTime     int64 `json:"created_time"`
}

type Task struct {
	Id          int64  `json:"id"`
	TaskPoolId  int64  `json:"task_pool_id"` // 任务池id
	Uid         int64  `json:"uid"`
	TaskType    int64  `json:"task_type"` // 任务类型 1入职2探索3邀请4奖励
	TaskName    string `json:"task_name"`
	TaskNameEn  string `json:"task_name_en"`
	Sort        int64  `json:"sort"` //排序
	Url         string `json:"url"`
	Integral    int64  `json:"integral"`    //积分
	IsComplete  int64  `json:"is_complete"` //是否完成 2未完成 1已完成
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type UserRes struct {
	Uid          int64  `json:"uid"`
	Name         string `json:"name"`          //用户名
	Avatar       string `json:"avatar"`        //头像
	Integral     int64  `json:"integral"`      //积分
	Storage      int64  `json:"storage"`       //存储空间
	StorageUse   int64  `json:"storage_use"`   //使用存储空间
	LanguageCode string `json:"language_code"` //语言代码 zh和en
	IsTips       bool   `json:"is_tips"`       // 是否提示
	IsRead       bool   `json:"is_read"`
}

type AddShareReq struct {
	Ids []int64 `json:"ids"` //资源ids
}

type AddShareResp struct {
	Link string `json:"link"` //链接
}

type AssetCallbackReq struct {
	Id   string `json:"id"`   // id
	Cid  string `json:"cid"`  // 资源id
	Link string `json:"link"` //链接地址
}

type AssetIdsReq struct {
	Ids []int64 `json:"ids"`
}

type AssetsInfoReq struct {
	Id int64 `form:"id"` //资源id
}

type BindUserWalletReq struct {
}

type BingConfirmReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"` //状态 2完成绑定3拒绝绑定
}

type BingUserReq struct {
	Puid int64 `json:"puid"` //绑定用户的uid
}

type CheckRecycleRes struct {
	IsRecycle bool `json:"is_recycle"` //是否回收
}

type ClaimRewardResp struct {
	RewardPoints int64 `json:"reward_points"` //奖励积分
}

type CloudDownloadReq struct {
	Id int64 `json:"id"` //id
}

type CloudDownloadResp struct {
	Flie      []byte `json:"file,optional"` //文件
	AssetName string `json:"asset_name"`    //资源名称
	AssetSize int64  `json:"asset_size"`    //资源大小
}

type CloudLinkReq struct {
	Id          int64    `json:"id,optional"`           //id 上传失败传入
	Pid         int64    `json:"pid"`                   //文件目录 默认从1开始
	Source      int64    `json:"source"`                //来源 1TDriver2云上传3Telegram
	TransitType int64    `json:"transit_type,optional"` //上传类型 1云链接 2TG 3X 4TK 5种子
	Link        []string `json:"link,optional"`         //链接
	AssetName   []string `json:"asset_name,optional"`   //资源名称
	AssetSize   []int64  `json:"asset_size,optional"`   //资源大小
}

type CopyReq struct {
	Ids []int64 `json:"ids"`
	Pid int64   `json:"pid"` //文件目录
}

type CreateAssetFileReq struct {
	Pid       int64  `json:"pid,optional"`        //文件目录 默认从1开始
	Source    int64  `json:"source"`              //来源 1TDriver2云上传3Telegram
	AssetName string `json:"asset_name"`          //资源名称
	AssetSize int64  `json:"asset_size,optional"` //资源大小
	Path      string `json:"path,optional"`       //文件路径
}

type CreateAssetFileResp struct {
	Id string `json:"id"` //id
}

type CreateAssetsReq struct {
	Pid         int64  `json:"pid,optional"`          //文件目录 默认从1开始
	Source      int64  `json:"source"`                //来源 1TDriver2云上传3Telegram
	TransitType int64  `json:"transit_type,optional"` //上传类型 1上传文件夹2上传文件3云链接 4TG 5X 6TK 7种子
	AssetName   string `json:"asset_name"`            //资源名称
	AssetSize   int64  `json:"asset_size,optional"`   //资源大小
}

type CreateAssetsResp struct {
	Id int64 `json:"id"` //资源id
}

type CreateFolderReq struct {
	Pid         int64  `json:"pid"`                   //文件目录 根目录从1开始
	Source      int64  `json:"source"`                //来源 1TDriver2云上传3Telegram
	TransitType int64  `json:"transit_type,optional"` //上传类型 1上传文件夹2上传文件3云链接 4TG 5X 6TK 7种子
	AssetName   string `json:"asset_name,optional"`   //资源名称
}

type DefaultRes struct {
	Id        int64  `json:"id"`         //默认文件id
	AssetName string `json:"asset_name"` //默认文件名称
}

type DelReq struct {
	Ids []int64 `json:"ids"`
}

type DelShareReq struct {
	Id int64 `json:"id"`
}

type DelTransmissionReq struct {
	Id       []string `json:"id"`
	IsSource bool     `json:"is_source"` // 是否删除源文件
}

type DocumentReq struct {
	AssetName  string  `json:"asset_name,optional"`  //资源名称
	Pid        int64   `json:"pid,optional"`         //文件目录 根目录从1开始
	IsTag      int64   `json:"is_tag,optional"`      //是否标记
	IsDel      bool    `json:"is_del,optional"`      //查询回收站
	AssetTypes []int64 `json:"asset_types,optional"` //资源类型 1文件夹2文件3视频4图片
	Page       int64   `json:"page,optional"`
	Size       int64   `json:"size,optional"`
	Order      int64   `json:"order,optional"`  //排序 0创建时间1修改时间2文件大小3文件名
	Sort       int64   `json:"sort,optional"`   //升序还是降序 0降序1升序
	IsAdd      bool    `json:"is_add,optional"` //查询最近添加的
}

type DocumentRes struct {
	Total      int64        `json:"page"` // 页码
	AssetItems []*AssetItem `json:"asset_items"`
}

type EstimatePointsReq struct {
	Storage int64 `form:"storage"` //空间
}

type EstimatePointsResp struct {
	Points int64 `json:"points"` //积分
}

type EstimateStorageResp struct {
	Points  int64 `json:"points"`  //积分
	Storage int64 `json:"storage"` //空间
}

type ExchangeReq struct {
	Storage int64 `json:"storage"` //空间
}

type ExchangeStorageReq struct {
	Storage int64 `json:"storage"` //空间
}

type GetShareReq struct {
	Id int64 `form:"id"`
}

type GetShareURLReq struct {
	UUID string `path:"uuid"`
}

type GuideReq struct {
	LuckyPoints int64 `json:"lucky_points"` //幸运积分
}

type GuideRewardReq struct {
	Year int `form:"year"` //年限
}

type GuideRewardRes struct {
	Uid         int64   `json:"uid"`          //uid
	Year        float64 `json:"year"`         //档位
	Top         int64   `json:"top"`          //排名
	YearPoints  int64   `json:"year_points"`  //年份积分
	LuckyPoints int64   `json:"lucky_points"` //幸运积分
	TgPoints    int64   `json:"tg_points"`    //tg会员奖励积分
	NewUser     int64   `json:"new_user"`     // 新用户固定积分
}

type InTransitReq struct {
	Status []int64 `json:"status"`          //状态 1禁用2进行中3完成4失败
	IsAdd  bool    `json:"is_add,optional"` //查询最近添加的
}

type InTransitRes struct {
	List []*InTransit `json:"list"`
}

type IsTagAssetFileReq struct {
	Id      string `json:"id"`       //id
	AssetId int64  `json:"asset_id"` //资源id
	IsTag   int64  `json:"is_tag"`   //是否标记 1是2否
}

type IsTagReq struct {
	Id    int64 `json:"id"`     //资源id
	IsTag int64 `json:"is_tag"` //是否标记 1是2否
}

type ListReq struct {
	Status []int64 `json:"status"`          //状态 1禁用2进行中3完成4失败
	IsAdd  bool    `json:"is_add,optional"` //查询最近添加的
	Page   int64   `json:"page,optional"`
	Size   int64   `json:"size,optional"`
}

type ListRes struct {
	Total int64        `json:"total"`
	List  []*AssetFile `json:"list"`
}

type LoginReq struct {
	RecommendCode string `json:"recommend_code,optional"` //推荐码
	IsShare       int64  `json:"is_share,optional"`       //是否是分享登录 1是
}

type MessageListResp struct {
	Total int64          `json:"total"`
	Items []*MessageItem `json:"items"`
}

type MoveReq struct {
	Ids []int64 `json:"ids"`
	Pid int64   `json:"pid"` //文件目录
}

type QueryShareReq struct {
	Page int64 `form:"page"` // 页码
	Size int64 `form:"size"` // 条数
}

type QueryShareResp struct {
	Shares []*Share `json:"shares"` //shares
	Total  int64    `json:"page"`   // 页码
}

type RackingListReq struct {
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type RackingListRes struct {
	Rackings []*Racking `json:"rackings"` //列表
	Total    int64      `json:"total"`
	Racking  *Racking   `json:"racking"` //自己
}

type ReceivePointsReq struct {
	Lon string `json:"lon"`
	Lat string `json:"lat"`
}

type RenewalReq struct {
	Token string `json:"token"`
}

type RenewalResp struct {
	TitanToken string `json:"titan_token"` //titan token
	Exp        int64  `json:"exp"`         //有效期
}

type ReportReq struct {
	Cid        string `json:"cid"`
	ReportType int64  `json:"report_type"` //举报类型 1色情2恐怖3暴力4虐待
}

type RetryReq struct {
	Id string `form:"id"`
}

type RewardListReq struct {
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type RewardListRes struct {
	UserTotal    int64     `json:"user_total"`    //已经引荐用户总数
	PointsTotal  int64     `json:"points_total"`  //已经获得积分
	StorageTotal int64     `json:"storage_total"` //已经获得空间
	Rewards      []*Reward `json:"rewards"`       //列表
	Total        int64     `json:"total"`         //总数
}

type RnameReq struct {
	Id        int64  `json:"id"`
	AssetName string `json:"asset_name"` //资源名称
}

type SaveAssetsReq struct {
	Ids []int64 `json:"ids"` //资源ids
}

type SaveAssetsResp struct {
	Id        int64  `json:"id"`         //保存文件夹的id
	AssetName string `json:"asset_name"` //保存文件夹的名称
}

type SetPassReq struct {
	Id   int64  `json:"id"`
	Pass string `json:"pass"`
}

type SetTimeReq struct {
	Id  int64 `json:"id"`
	Day int   `json:"day"` //有效时间
}

type TaskCompleteReq struct {
	Id         int64 `json:"id"`
	TaskPoolId int64 `json:"task_pool_id"`
	Integral   int64 `json:"integral,omitempty"` //积分
}

type TaskCompleteResp struct {
	Integral int64 `json:"integral"` //积分
}

type TaskListRes struct {
	Url   string  `json:"url"`
	Total int64   `json:"total"`
	Tasks []*Task `json:"tasks"`
}

type UpdateTransmissionReq struct {
	Id  string `json:"id"`
	Err string `json:"err"` // 错误信息
}

type UploadFileReq struct {
	Flie      []byte `json:"file,optional"`       //文件
	Id        string `json:"id,optional"`         //资源id
	AssetName string `json:"asset_name,optional"` //资源名称
	AssetSize int64  `json:"asset_size,optional"` //资源大小
}

type UploadReq struct {
	Flie      []byte `json:"file,optional"`       //文件
	Id        int64  `json:"id,optional"`         //资源id
	AssetName string `json:"asset_name,optional"` //资源名称
	AssetSize int64  `json:"asset_size,optional"` //资源大小
}

type UserRecommendPlanRes struct {
	Url          string      `json:"url"`           //邀请链接
	DictItems    []*DictItem `json:"dict_items"`    //引荐奖励
	ActivityRule string      `json:"activity_rule"` //活动规则
	Describe     string      `json:"describe"`      //描述
	RewardPoints int64       `json:"reward_points"` //奖励积分
	Total        int64       `json:"total"`         //朋友总数
	List         []*Friend   `json:"list"`          //朋友列表
}

type UserSpaceReq struct {
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type UserSpaceResp struct {
	Total int64        `json:"total"`
	List  []*SpaceItem `json:"list"`
}
