// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videosFieldNames          = builder.RawFieldNames(&Videos{})
	videosRows                = strings.Join(videosFieldNames, ",")
	videosRowsExpectAutoSet   = strings.Join(stringx.Remove(videosFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	videosRowsWithPlaceHolder = strings.Join(stringx.Remove(videosFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheVideosIdPrefix = "cache:videos:id:"
)

type (
	videosModel interface {
		Insert(ctx context.Context, data *Videos, s ...sqlx.Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*Videos, error)
		FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*Videos, error)
		Update(ctx context.Context, data *Videos, s ...sqlx.Session) error
		ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*Videos, int64, error)
		List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*Videos, error)
		Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error)
		Delete(ctx context.Context, id int64, s ...sqlx.Session) error
	}

	defaultVideosModel struct {
		sqlc.CachedConn
		table string
	}

	Videos struct {
		Id          int64  `db:"id"`
		Uid         int64  `db:"uid"`
		Title       string `db:"title"`     // 视频标题
		Desc        string `db:"desc"`      // 视频描述
		Filename    string `db:"filename"`  // 视频名称
		Cid         string `db:"cid"`       // 资源id
		Link        string `db:"link"`      // 视频地址
		FilePath    string `db:"file_path"` // 视频文件在服务器上的存储路径
		Status      int64  `db:"status"`    // 状态 1禁用2完成
		CreatedTime int64  `db:"created_time"`
		UpdatedTime int64  `db:"updated_time"`
		DeletedTime int64  `db:"deleted_time"`
	}
)

func newVideosModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultVideosModel {
	return &defaultVideosModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`videos`",
	}
}

func (m *defaultVideosModel) Delete(ctx context.Context, id int64, s ...sqlx.Session) error {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, id)

	var query string
	if VideosSoftDelete {
		query = fmt.Sprintf("update %s set `deleted_time` = %v where `id` = ?", m.table, time.Now().Unix())
	} else {
		query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
	}

	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if s != nil {
			return s[0].ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, videosIdKey)
	return err
}

func (m *defaultVideosModel) FindOne(ctx context.Context, id int64, s ...sqlx.Session) (*Videos, error) {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, id)
	var resp Videos
	err := m.QueryRowCtx(ctx, &resp, videosIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videosRows, m.table)
		if s != nil {
			return s[0].QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideosModel) Insert(ctx context.Context, data *Videos, s ...sqlx.Session) (sql.Result, error) {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, videosRowsExpectAutoSet)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.Title, data.Desc, data.Filename, data.Cid, data.Link, data.FilePath, data.Status, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Title, data.Desc, data.Filename, data.Cid, data.Link, data.FilePath, data.Status, data.CreatedTime, data.UpdatedTime, data.DeletedTime)
	}, videosIdKey)
}

func (m *defaultVideosModel) Update(ctx context.Context, data *Videos, s ...sqlx.Session) error {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videosRowsWithPlaceHolder)
		if s != nil {
			return s[0].ExecCtx(ctx, query, data.Uid, data.Title, data.Desc, data.Filename, data.Cid, data.Link, data.FilePath, data.Status, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Title, data.Desc, data.Filename, data.Cid, data.Link, data.FilePath, data.Status, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Id)
	}, videosIdKey)
	return err
}

func (m *defaultVideosModel) FindOneByBuilder(ctx context.Context, sbs ...squirrel.SelectBuilder) (*Videos, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(videosRows).Limit(1).ToSql()
	if err != nil {
		return nil, err
	}
	var ret Videos
	if err := m.QueryRowNoCacheCtx(ctx, &ret, query, args...); err != nil {
		return nil, err
	}

	return &ret, nil
}

func (m *defaultVideosModel) ListPage(ctx context.Context, page, size int64, sbs ...squirrel.SelectBuilder) ([]*Videos, int64, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// count builder
	cb := sb.Column("Count(*) as count").From(m.table)
	query, args, err := cb.ToSql()
	if err != nil {
		return nil, 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return nil, 0, err
	}

	// query rows
	if page <= 0 {
		page = 1
	}
	query, args, err = sb.From(m.table).Columns(videosRows).Offset(uint64((page - 1) * size)).Limit(uint64(size)).ToSql()
	if err != nil {
		return nil, 0, err
	}
	var list []*Videos
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *defaultVideosModel) List(ctx context.Context, sbs ...squirrel.SelectBuilder) ([]*Videos, error) {
	var sb squirrel.SelectBuilder
	if sbs == nil {
		sb = squirrel.Select()
	} else {
		sb = sbs[0]
	}

	// query rows
	query, args, err := sb.From(m.table).Columns(videosRows).ToSql()
	if err != nil {
		return nil, err
	}
	var list []*Videos
	if err := m.QueryRowsNoCacheCtx(ctx, &list, query, args...); err != nil {
		return nil, err
	}

	return list, nil
}

func (m *defaultVideosModel) Count(ctx context.Context, cbs ...squirrel.SelectBuilder) (int64, error) {
	var cb squirrel.SelectBuilder
	if cbs == nil {
		cb = squirrel.Select()
	} else {
		cb = cbs[0]
	}

	// count builder
	query, args, err := cb.Column("Count(*) as count").From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var total int64
	if err := m.QueryRowNoCacheCtx(ctx, &total, query, args...); err != nil {
		return 0, err
	}

	return total, err
}

func (m *defaultVideosModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheVideosIdPrefix, primary)
}

func (m *defaultVideosModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videosRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVideosModel) tableName() string {
	return m.table
}

var VideosSoftDelete bool

func init() {
	tp := reflect.TypeOf(Videos{})
	for i := 0; i < tp.NumField(); i++ {
		if tp.Field(i).Tag.Get("db") == "deleted_time" {
			VideosSoftDelete = true
			return
		}
	}
}
