// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

var prefixVideos_commentCacheKey = "cache:videos_comment:"

type videos_commentModel interface {
	Insert(ctx context.Context, data *Videos_comment) error
	FindOne(ctx context.Context, id string) (*Videos_comment, error)
	Update(ctx context.Context, data *Videos_comment) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultVideos_commentModel struct {
	conn *monc.Model
}

func newDefaultVideos_commentModel(conn *monc.Model) *defaultVideos_commentModel {
	return &defaultVideos_commentModel{conn: conn}
}

func (m *defaultVideos_commentModel) Insert(ctx context.Context, data *Videos_comment) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixVideos_commentCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultVideos_commentModel) FindOne(ctx context.Context, id string) (*Videos_comment, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Videos_comment
	key := prefixVideos_commentCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideos_commentModel) Update(ctx context.Context, data *Videos_comment) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	key := prefixVideos_commentCacheKey + data.ID.Hex()
	res, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultVideos_commentModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}
	key := prefixVideos_commentCacheKey + id
	res, err := m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return res, err
}
