// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

var prefixVideos_replyCacheKey = "cache:videos_reply:"

type videos_replyModel interface {
	Insert(ctx context.Context, data *Videos_reply) error
	FindOne(ctx context.Context, id string) (*Videos_reply, error)
	Update(ctx context.Context, data *Videos_reply) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultVideos_replyModel struct {
	conn *monc.Model
}

func newDefaultVideos_replyModel(conn *monc.Model) *defaultVideos_replyModel {
	return &defaultVideos_replyModel{conn: conn}
}

func (m *defaultVideos_replyModel) Insert(ctx context.Context, data *Videos_reply) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixVideos_replyCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultVideos_replyModel) FindOne(ctx context.Context, id string) (*Videos_reply, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Videos_reply
	key := prefixVideos_replyCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideos_replyModel) Update(ctx context.Context, data *Videos_reply) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	key := prefixVideos_replyCacheKey + data.ID.Hex()
	res, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultVideos_replyModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}
	key := prefixVideos_replyCacheKey + id
	res, err := m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return res, err
}
